# Generated by Django 5.2.4 on 2025-07-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_address', models.TextField(blank=True, null=True)),
                ('seller_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('seller_pan', models.CharField(blank=True, max_length=20, null=True)),
                ('seller_gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_holder', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('HSN_codes', models.JSONField(blank=True, default=list, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
        ),
    ]
