# Generated by Django 5.2.4 on 2025-07-13 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_address', models.TextField()),
                ('buyer_gst', models.CharField(blank=True, max_length=20, null=True)),
                ('consignee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('consignee_address', models.TextField(blank=True, null=True)),
                ('consignee_gst', models.CharField(blank=True, max_length=20, null=True)),
                ('financial_year', models.CharField(default='2025-2026', max_length=9)),
                ('invoice_number', models.CharField(default='01-2025/2026', max_length=20)),
                ('invoice_date', models.DateField()),
                ('delivery_note', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('payment_mode', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('delivery_note_date', models.DateField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('terms_to_delivery', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('country', models.CharField(default='India', max_length=255)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('state', models.CharField(default='Gujarat', max_length=50)),
                ('particulars', models.CharField(blank=True, default='Consultancy', max_length=255, null=True)),
                ('total_hours', models.FloatField(blank=True, default=0.0, null=True)),
                ('rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('base_amount', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('cgst', models.FloatField(blank=True, default=0.0, null=True)),
                ('sgst', models.FloatField(blank=True, default=0.0, null=True)),
                ('igst', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_with_gst', models.FloatField()),
                ('amount_in_words', models.CharField(blank=True, max_length=255, null=True)),
                ('taxtotal', models.FloatField(blank=True, default=0.0, null=True)),
                ('remark', models.TextField(blank=True, default='', null=True)),
                ('exchange_rate', models.FloatField(blank=True, default=1.0, null=True)),
                ('inr_equivalent', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_flag', models.URLField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
