# Generated by Django 5.2.4 on 2025-07-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_buyer_delete_buyerbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notice', models.TextField(blank=True, null=True)),
                ('payment_type', models.CharField(max_length=50)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('manual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('notice', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(max_length=50)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notice', models.TextField(blank=True, null=True)),
                ('payment_type', models.CharField(max_length=50)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(max_length=50)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
