# Generated by Django 5.2.4 on 2025-07-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_buyername'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyerName',
        ),
    ]
