# Generated by Django 5.2.4 on 2025-07-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_othertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='othertransaction',
            name='buyer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='othertransaction',
            name='buyer_gst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='othertransaction',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
