# Generated by Django 5.2.4 on 2025-07-22 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_othertransaction_buyer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othertransaction',
            name='buyer_address',
        ),
        migrations.RemoveField(
            model_name='othertransaction',
            name='buyer_gst',
        ),
        migrations.RemoveField(
            model_name='othertransaction',
            name='buyer_name',
        ),
        migrations.AddField(
            model_name='othertransaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
