# Generated by Django 5.2 on 2025-07-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_invoice_hns_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_tax_in_words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
