# Generated by Django 5.2.4 on 2025-07-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_balancesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='othertransaction',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='othertransaction',
            name='partner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
