# Generated by Django 5.2.4 on 2025-07-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_invoice_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('invoice_date', models.DateField()),
                ('total_tax_amount', models.FloatField(blank=True, null=True)),
                ('total_with_gst', models.FloatField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('financial_year', models.CharField(max_length=9)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
