# Generated by Django 5.2.4 on 2025-07-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_archivedinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othertransaction',
            old_name='partner_name',
            new_name='name',
        ),
    ]
