# Generated by Django 5.2 on 2025-07-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_partner_name_othertransaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_opening_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='is_opening_balance',
            field=models.BooleanField(default=False),
        ),
    ]
