# Generated by Django 5.2 on 2025-07-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_bankaccount_is_opening_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('type', 'name')},
            },
        ),
    ]
