# Generated by Django 5.2 on 2025-07-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_othername'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherName',
        ),
    ]
