# Generated by Django 5.2 on 2025-07-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_othername'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherName',
        ),
    ]
