# Generated by Django 5.2 on 2025-07-30 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_delete_othername'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherType',
        ),
        migrations.RemoveField(
            model_name='employeeactionhistory',
            name='details',
        ),
        migrations.AlterField(
            model_name='employeeactionhistory',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeactionhistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
