# Generated by Django 5.2 on 2025-07-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_delete_othertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
