# Generated by Django 5.2 on 2025-07-30 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_buyer_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyerBill',
        ),
        migrations.AddField(
            model_name='buyer',
            name='manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='payment_type',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash')], default='Bank', max_length=50),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to=settings.AUTH_USER_MODEL),
        ),
    ]
